import { Router } from 'express';
import { getAllProjects, getProject, createProject, updateProject, deleteProject } from '../controllers/projectController.js';
import { requireAuth } from '../middleware/auth.js';
const router = Router();
router.get('/', getAllProjects);
router.get('/:id', getProject);
router.post('/', requireAuth, createProject);
router.put('/:id', requireAuth, updateProject);
router.delete('/:id', requireAuth, deleteProject);
export default router;
